version: 2.1

references:
  workspace_root: &workspace_root "/home/circleci/workspace"

jobs:
  run-tests:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout:
          path: *workspace_root
      - run:
          command: |
            ./runTests.sh
      - store_artifacts:
          path: "coverage"

workflows:

  full_workflow:
    jobs:
      - run-tests
